import { NextRequest } from "next/server";
import { promises as fs } from "fs";
import path from "path";

export const runtime = "nodejs";

export async function GET(_req: NextRequest) {
  try {
    // Read the PDF file generated by Python script
    const pdfPath = path.join(process.cwd(), "reports", "relations-investor-report.pdf");
    
    try {
      const pdfBuffer = await fs.readFile(pdfPath);
      
      return new Response(pdfBuffer, {
        status: 200,
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="relations-investor-report.pdf"`,
          "Cache-Control": "no-cache",
        },
      });
    } catch (fileErr: any) {
      // If PDF doesn't exist, return 404 with helpful message
      if (fileErr.code === "ENOENT") {
        return new Response(
          JSON.stringify({ 
            error: "PDF not yet generated. Run: python scripts/export/investor_pdf_v2.py",
            path: pdfPath 
          }),
          {
            status: 404,
            headers: { "Content-Type": "application/json" },
          }
        );
      }
      throw fileErr;
    }
  } catch (err: any) {
    console.error("[PDF] Failed to serve PDF:", err);
    return new Response(
      JSON.stringify({ error: String(err?.message || err) }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
