#!/usr/bin/env node
/**
 * SI Open PR
 * PR6: SI-loop scaffold
 * 
 * Creates draft PR with proposed golden cases
 */
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");

function run(cmd) {
  try {
    execSync(cmd, { cwd: ROOT, stdio: "inherit", shell: true });
    return true;
  } catch (error) {
    console.error(`[SI Open PR] Command failed: ${cmd}`);
    return false;
  }
}

function main() {
  console.log("[SI Open PR] Creating draft PR...");
  
  // Check if gh CLI is available
  try {
    execSync("gh --version", { stdio: "ignore" });
  } catch {
    console.error("[SI Open PR] GitHub CLI (gh) not found, skipping PR creation");
    console.log("[SI Open PR] Run: git add . && git commit -m 'SI: proposals'");
    return;
  }
  
  // Create branch
  const timestamp = Date.now();
  const branch = `si/${timestamp}`;
  
  console.log(`[SI Open PR] Creating branch: ${branch}`);
  
  if (!run(`git checkout -b ${branch}`)) {
    console.error("[SI Open PR] Failed to create branch");
    return;
  }
  
  // Apply proposals
  console.log("[SI Open PR] Applying proposals...");
  
  if (!run(`node scripts/apply_si_proposals.mjs`)) {
    console.error("[SI Open PR] Failed to apply proposals");
    return;
  }
  
  // Check if there are changes
  try {
    const status = execSync("git status --porcelain", {
      cwd: ROOT,
      encoding: "utf-8",
      stdio: "pipe"
    });
    
    if (!status.trim()) {
      console.log("[SI Open PR] No changes to commit");
      run(`git checkout main`);
      run(`git branch -D ${branch}`);
      return;
    }
  } catch (error) {
    console.warn("[SI Open PR] Could not check git status");
  }
  
  // Stage changes
  console.log("[SI Open PR] Staging changes...");
  
  if (!run(`git add tests/golden/** reports/si/proposals.jsonl`)) {
    console.error("[SI Open PR] Failed to stage changes");
    return;
  }
  
  // Commit
  const msg = "SI: add proposed golden cases (memory/emotion)";
  console.log("[SI Open PR] Committing...");
  
  if (!run(`git commit -m "${msg}"`)) {
    console.error("[SI Open PR] Failed to commit");
    return;
  }
  
  // Push
  console.log("[SI Open PR] Pushing...");
  
  if (!run(`git push -u origin ${branch}`)) {
    console.error("[SI Open PR] Failed to push");
    return;
  }
  
  // Create draft PR
  console.log("[SI Open PR] Creating draft PR...");
  
  if (!run(`gh pr create --title "${msg}" --body "Auto-generated by SI loop" --draft`)) {
    console.error("[SI Open PR] Failed to create PR");
    return;
  }
  
  console.log("[SI Open PR] Draft PR created successfully");
}

main();

